# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c47065a15b42614754d38af67693e8067fdc6bdd31a01b5f8fb178eb06f8a2bb03a55c9e0f39ecda50c4ce5fad64ef980f0df0a31f73cb85bd727c373dec7fe1

test:
  secret_key_base: 2f325e3eea779b85bd194f207ffc877865d20c7e3d533c325b49d722dfa8c34f4b216bd600525ef8aa0512099758ec62f27729865694945bd10e59ce454c1fe4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
